version: '3.8'

services:
  database:
    image: postgres:16.10-alpine3.22
    container_name: tanya-luna-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-host
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "topic-test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # api-service:
  #   build: ./api-service
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     KAFKA_BROKERS: kafka-host:9092
  #   depends_on:
  #     - kafka

  # booking-service:
  #   build: ./booking-service
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     KAFKA_BROKERS: kafka-host:9092
  #   depends_on:
  #     - kafka
volumes:
  postgres_data: